<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        /*
         * The key columns are capped at 191 characters.
         *
         * Laravel's default is varchar(255). On MySQL with utf8mb4 a character
         * is 4 bytes, so 255 * 4 = 1020 bytes — over the 1000-byte limit MySQL
         * allows for a PRIMARY KEY on this configuration, and the migration
         * fails with "Specified key was too long; max key length is 1000 bytes".
         *
         * 191 * 4 = 764 bytes, which fits. Cache keys are generated by Laravel
         * and are far shorter than 191 characters in practice, so this costs
         * nothing. (Laravel's own docs recommend exactly this length for the
         * same reason.)
         */
        Schema::create('cache', function (Blueprint $table) {
            $table->string('key', 191)->primary();
            $table->mediumText('value');
            $table->bigInteger('expiration')->index();
        });

        Schema::create('cache_locks', function (Blueprint $table) {
            $table->string('key', 191)->primary();
            $table->string('owner');
            $table->bigInteger('expiration')->index();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('cache');
        Schema::dropIfExists('cache_locks');
    }
};
